services:
  - type: web
    name: nuviostreams
    runtime: docker
    plan: free
    autoDeploy: true
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /manifest.json
    envVars:
      - key: PORT
        value: "7000"
      - key: TMDB_API_KEY
        sync: false
